<S> ::= <RUN_CODE_ACTIONS> [1]

<RUN_CODE_ACTIONS> ::= <RUN_CODE_ACTION> [0.35]
<RUN_CODE_ACTIONS> ::= <RUN_CODE_ACTION> <RUN_CODE_ACTIONS> [0.65]
<RUN_CODE_ACTION> ::= ahead <DISTANCE_VALUE> [0.2]
<RUN_CODE_ACTION> ::= back <DISTANCE_VALUE> [0.1]
<RUN_CODE_ACTION> ::= turn_right <DEGREES_VALUE> [0.35]
<RUN_CODE_ACTION> ::= turn_left <DEGREES_VALUE> [0.35]
<DISTANCE_VALUE> ::= 20 [0.2]
<DISTANCE_VALUE> ::= 40 [0.2]
<DISTANCE_VALUE> ::= 60 [0.2]
<DISTANCE_VALUE> ::= 80 [0.2]
<DISTANCE_VALUE> ::= 100 [0.2]
<DEGREES_VALUE> ::= 5 [0.25]
<DEGREES_VALUE> ::= 15 [0.25]
<DEGREES_VALUE> ::= 30 [0.25]
<DEGREES_VALUE> ::= 45 [0.25]
